<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MaintainLog extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('latest', function (Builder $builder) {
            $builder->latest();
        });
    }


    public function device()
    {
        return $this->belongsTo('App\Models\Device');
    }

    public function check_item_logs()
    {
        return $this->belongsToMany('App\Models\DeviceCheckItem', 'device_check_item_log', 'maintain_log_id', 'device_check_item_id')->withTimestamps()->withPivot('result');
    }

    public function getResultTextAttribute()
    {
        return $this->attributes['result'] ? '正常' : '异常';
    }

    public function setPhotosAttribute($value)
    {
        $this->attributes['photos'] = json_encode($value);
    }

    public function getPhotosAttribute()
    {
        return json_decode($this->attributes['photos']);
    }
}
